# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Doublemine
subtitle:
description: Keep fucking the world
author: 夏末
language: zh-Hans
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://notes.wanghao.work
root: /
# 设置永久链接
permalink: :year-:month-:day-:title.html
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
#category: 1
#tag: 1
#archive: 1
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
#per_page: 5
pagination_dir: page

#自定义配置

index_generator:
  per_page: 5

archive_generator:
  per_page: 20
  yearly: true
  monthly: true

tag_generator:
  per_page: 10


# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: hexo-theme-next

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repo:
    github: git@github.com:Doublemine/Doublemine.github.io.git,master
    # gitcafe: git@gitcafe.com:smilexiamo/smilexiamo.git,gitcafe-pages
    #notes: ssh://git@server.wanghao.work:1314/home/nginx-soft/nginx/git_blog_notes.git,master


rss:


# plugins:
# - hexo-generator-sitemap
# - hexo-generator-feed
# - hexo-generator-baidu-sitemap
# - hexo-generator-robotstxt
# - hexo-qiniu-sync




#以下针对HEXO -NEXT主题

#baidu_analytics: 8288c8dbaec733837ad8e70bbe056a1f


#tinysou_Key: 7bcfcc04320003ff9fb6
creative_commons: by-nc-sa
#baidushare: true

duoshuo_share: true
duoshuo_shortname: doublemine
since: 2015
social:
  Twitter: https://twitter.com/_xiamo
  Instagram: https://www.instagram.com/___xiamo/
  GitHub: https://github.com/doublemine
  Weibo: http://weibo.com/wanghao19940820

#以下为友情链接
links_title: 友情链接
# links
links:
  Kevin: https://jiangtaoquite.github.io/
  kisence: http://www.kisence.com/

#qiniu:
#  offline: false
#  sync: true
#  bucket: notes
#  secret_file: qiniu.json
#  access_key:
#  secret_key:
#  dirPrefix: static
#  urlPrefix: http://7xkj6q.com1.z0.glb.clouddn.com/static
#  up_host: http://upload.qiniu.com
#  local_dir: static
#  update_exist: true
#  image:
#    folder: images
#    extend:
#  js:
#    folder: js
#  css:
#    folder: css
